#----------------------------------------------------
# Configuration
#----------------------------------------------------

# Compile debug version
CONFIG_DBG:=n

# Console
CONFIG_CONSOLE_ENABLED:=y

# Serial console
CONFIG_CONSOLE_SERIAL:=y
CONFIG_CONSOLE_SERIAL_PORT:=COM1

# Loader command line support
CONFIG_COMMAND_LINE_ENABLED:=y

# RAW images supporting
CONFIG_RAW_IMAGES_ENABLED=n

# Binary data will be additionaly scrambled using simple XOR
# based algorothm
CONFIG_SIMG_XOR_SCRAMBLED=y

#----------------------------------------------------
# Parameters
#----------------------------------------------------
#
# Disk
#
DISK_SECTOR_SIZE			:= 512
IO_BUFFER_ADDRESS			:= (KERNEL_SETUP_ADDRESS-DISK_SECTOR_SIZE)

#
# Disk map
#
LOADER_DESCRIPTOR_LBA		:= 22
LOADER_CODE_LBA				:= 32
KERNEL_CODE_LBA				:= 200

#
# Memory map
#
MBR_CODE_ADDRESS			:= 0x00007c00
LOADER_DESCRIPTOR_ADDRESS	:= 0x00007800
LOADER_CODE_ADDRESS			:= 0x00008000
LOADER_STACK_ADDRESS		:= 0x00007600

# bzImage
KERNEL_SETUP_SECTORS		:= 4
KERNEL_REAL_CODE_ADDRESS	:= 0x00090000
KERNEL_CODE_ADDRESS			:= 0x00100000
LOADER_HEAP_START			:= 0x00800000
LOADER_HEAP_SIZE			:= 0x00800000

# Environment

# zImage
#KERNEL_REAL_CODE_ADDRESS	:= 0x00090000
#KERNEL_CODE_ADDRESS		:= 0x00010000

#
# Images
#
HDD_IMG						:= hdd.raw

# Bochs share folder
export BXSHARE				:= /usr/share/bochs

# Kernel image
#BZIMAGE					:= bzImage
BZIMAGE						:= ../../00_kernels/kbuild/arch/x86/boot/bzImage

