#-----------------------------------------------------------------------------------
CONFIG-DBG-y					:= -ggdb3 -O0 -D__DEBUG__ -Wall
CONFIG-DBG-n					:= -O2
CONFIG-CONSOLE-ENABLED-y 		:= -DCONFIG_CONSOLE_ENABLED
CONFIG-CONSOLE-SERIAL-y 		:= -DCONFIG_CONSOLE_SERIAL
CONFIG-CONSOLE-SERIAL-PORT-COM1 := -DCONFIG_CONSOLE_SERIAL_PORT=COM1
CONFIG-CONSOLE-SERIAL-PORT-COM2 := -DCONFIG_CONSOLE_SERIAL_PORT=COM2
CONFIG-CONSOLE-SERIAL-PORT-COM3 := -DCONFIG_CONSOLE_SERIAL_PORT=COM3
CONFIG-CONSOLE-SERIAL-PORT-COM4 := -DCONFIG_CONSOLE_SERIAL_PORT=COM4
CONFIG-COMMAND-LINE-ENABLED-y	:= -DCONFIG_COMMAND_LINE_ENABLED
CONFIG-RAW-IMAGES-ENABLED-y		:= -DCONFIG_RAW_IMAGES_ENABLED
CONFIG-SIMG-XOR-SCRAMBLED-y		:= -DCONFIG_SIMG_XOR_SCRAMBLED
CONFIG-SIMG-ENCRYPTION-blowfish	:= -DCONFIG_SIMG_BLOWFISH_ENCRYPTED

#-----------------------------------------------------------------------------------
DEFINES			+= $(CONFIG-CONSOLE-ENABLED-$(CONFIG_CONSOLE_ENABLED))
DEFINES			+= $(CONFIG-CONSOLE-SERIAL-$(CONFIG_CONSOLE_SERIAL))
DEFINES			+= $(CONFIG-CONSOLE-SERIAL-PORT-$(CONFIG_CONSOLE_SERIAL_PORT))
DEFINES			+= $(CONFIG-COMMAND-LINE-ENABLED-$(CONFIG_COMMAND_LINE_ENABLED))
DEFINES			+= $(CONFIG-RAW-IMAGES-ENABLED-$(CONFIG_RAW_IMAGES_ENABLED))
DEFINES			+= $(CONFIG-SIMG-XOR-SCRAMBLED-$(CONFIG_SIMG_XOR_SCRAMBLED))
DEFINES			+= $(CONFIG-SIMG-ENCRYPTION-$(CONFIG_SIMG_ENCRYPTION))

CDIR			:= $(shell pwd)

#INCLUDES		= -I$(CDIR)/ -I$(CDIR)/core -I$(CDIR)/linux

