#! /bin/sh

#--------------------------------------------------------------------
# (C) D.Iakovliev 2011-2012 (daemondzk@gmail.com)
#--------------------------------------------------------------------

function getline() {
	head -n$2 $1 | tail -n1
}

function formatarray {
	tmpf=`tempfile`
	result="`printf "unsigned char $1[] = { "`"
	echo "$2" > $tmpf
	while read -n2 byte 
	do
		if [ -n "$byte" ]; then
	 		result="$result`printf "0x%s," "${byte,,}"`"
		fi
	done < $tmpf
	result=`echo "$result" | sed "s/\(.*\)./\1/"`
	result="$result`printf " };"`"
	rm $tmpf
	echo $result
}

function formatsize() {
	echo "unsigned int $1_size = sizeof($1) / sizeof($1[0]);"
}

function formatheader() {
	echo "/* This file is automatically generated at `date`. Please do not modify. */"
}

#--------------------------------------------------------------------

TARGET_DIR=../crypt

# Cleanup
rm -f $TARGET_DIR/dsa_*
rm -f $TARGET_DIR/rsa_*

#---------------------------- DSA -----------------------------------
asn1file=`tempfile`
targetfile=$TARGET_DIR/dsa_key.c
openssl dsaparam 1024 < /dev/urandom > $TARGET_DIR/dsa_param.pem
openssl gendsa $TARGET_DIR/dsa_param.pem -out $TARGET_DIR/dsa_priv.pem
openssl asn1parse -inform PEM -in $TARGET_DIR/dsa_priv.pem -dump | sed s#^.*:##g > $asn1file
echo "$(formatheader)" > $targetfile
echo "$(formatarray "dsa_pub" "`getline $asn1file 6`")" >> $targetfile
echo "$(formatarray "dsa_P" "`getline $asn1file 3`")" >> $targetfile
echo "$(formatarray "dsa_Q" "`getline $asn1file 4`")" >> $targetfile
echo "$(formatarray "dsa_G" "`getline $asn1file 5`")" >> $targetfile
echo "$(formatsize "dsa_pub")" >> $targetfile
echo "$(formatsize "dsa_P")" >> $targetfile
echo "$(formatsize "dsa_Q")" >> $targetfile
echo "$(formatsize "dsa_G")" >> $targetfile
targetfile=$TARGET_DIR/dsa_pkey.c
echo "$(formatheader)" > $targetfile
echo "$(formatarray "dsa_priv" "`getline $asn1file 7`")" >> $targetfile
echo "$(formatsize "dsa_priv")" >> $targetfile
rm $asn1file

#---------------------------- RSA -----------------------------------
asn1file=`tempfile`
targetfile=$TARGET_DIR/rsa_pkey.c
openssl genrsa -out $TARGET_DIR/rsa_priv.pem 512
openssl asn1parse -inform PEM -in $TARGET_DIR/rsa_priv.pem -dump | sed s#^.*:##g > $asn1file
echo "$(formatheader)" > $targetfile
echo "$(formatarray "rsa_n" "`getline $asn1file 3`")" >> $targetfile
echo "$(formatarray "rsa_e" "`getline $asn1file 4`")" >> $targetfile
echo "$(formatarray "rsa_d" "`getline $asn1file 5`")" >> $targetfile
echo "$(formatarray "rsa_p" "`getline $asn1file 6`")" >> $targetfile
echo "$(formatarray "rsa_q" "`getline $asn1file 7`")" >> $targetfile
echo "$(formatarray "rsa_dmp1" "`getline $asn1file 8`")" >> $targetfile
echo "$(formatarray "rsa_dmq1" "`getline $asn1file 9`")" >> $targetfile
echo "$(formatarray "rsa_iqmp" "`getline $asn1file 10`")" >> $targetfile
echo "$(formatsize "rsa_n")" >> $targetfile
echo "$(formatsize "rsa_e")" >> $targetfile
echo "$(formatsize "rsa_d")" >> $targetfile
echo "$(formatsize "rsa_p")" >> $targetfile
echo "$(formatsize "rsa_q")" >> $targetfile
echo "$(formatsize "rsa_dmp1")" >> $targetfile
echo "$(formatsize "rsa_dmq1")" >> $targetfile
echo "$(formatsize "rsa_iqmp")" >> $targetfile
rm $asn1file

